language: go

go:
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false
#  irc: "irc.freenode.org#victi.ms"
#  skip_join: false

# Required since the clone will not always be tested from inside the victims namespace
before_script:
  - mkdir -p $HOME/gopath/src/github.com/victims/victims-common/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/victims/victims-common/

script:
  - make deps
  - make check
  - make build
